### ISSUE TITLE
Remove slide functionality

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-guide#25]
We want to abandon the slide paradigm in favor of a simple, linear document approach.

**TODO:**
- [x] **1.** Identify which (if any) chapters we want to keep that are currently leveraging slides. Of those, replace each [slide include](https://user-images.githubusercontent.com/8367927/73299250-af146900-41c3-11ea-9e92-b026a094062d.png) in the chapter markdown with inline content copied and pasted from the corresponding slide markdown
- [x] **2.** Remove `reveal.js` library and associated components
- [x] **3.** Remove slide references from the content
- [x] **4.** Remove [slides folder](https://user-images.githubusercontent.com/8367927/73300062-32828a00-41c5-11ea-8de8-ca5713133990.png) from repo

<br>

![image](https://user-images.githubusercontent.com/8367927/73299102-68267380-41c3-11ea-8b2f-71afd277b81e.png)
