### ISSUE TITLE
Replace all SASS with Varnish + Styled Components

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-guide#41]
**TODO**
- [x] 1. Add Varnish library and dependencies to `package.json`
- [x] 2. Update `package-lock.json`
- [x] 3. Pull in external Varnish CSS file via `<link>` in `<head>`
- [x] 4. Refactor template and component markup to used styled components
- [x] 5. Rename components as needed
- [x] 6. Improve code style as needed (e.g. consistent indenting, adding semicolons, etc.)
- [x] 7. Convert any `sass`-driven style that we want to keep into Varnish-friendly styled components.
- [x] 8. Remove sass from project
